### ISSUE TITLE
Hymmnos font download 1.1 actually 1.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [flan/hymmnoserver#4]
```
Downloading Hymmnos font ver. 1.1 actually gives you ver. 1.0.


```

Original issue reported on code.google.com by `Mater...@gmail.com` on 24 Jul 2011 at 10:20

**Comment by flan** [comment]
I know you submitted this four and a half years ago, but I just migrated the code to github and Google Code still thought this issue was still open, so sorry for the way-outdated e-mail you might get when I click close.
